export const CART_CREATION_REQUEST = 'CART_CREATION_REQUEST'
export const CART_CREATION_SUCCESS = 'CART_CREATION_SUCCESS'
export const CART_CREATION_FAIL = 'CART_CREATION_FAIL'

export const ADD_CART_REQUEST = 'ADD_CART_REQUEST'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAIL = 'ADD_CART_FAIL'

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL'

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'
